/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citybattle_v2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michail Sitmalidis
 */
public class MainFrame extends javax.swing.JFrame {

    private Thread thread;
    private Boolean Go;
    private int tikerKeeper;

    private BattleField battleField;

    public MainFrame() {
        Go = false;
        initComponents();
        init();
        battleField = new BattleField();
        add(battleField);
        battleField.repaint();
        thread = new Thread(new GameTicker());//this thread is for game loop to run
        thread.start();
        //---this is temporary 

        //  jButton3.doClick();
        //   jButton4.doClick();
        jButton6.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        walk = new javax.swing.JRadioButton();
        putBrick = new javax.swing.JRadioButton();
        putSteel = new javax.swing.JRadioButton();
        putWater = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Start Building");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BRICKS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("MyTank");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        buttonGroup1.add(walk);
        walk.setSelected(true);
        walk.setText("WALK");

        buttonGroup1.add(putBrick);
        putBrick.setText("PUT BRICK");

        buttonGroup1.add(putSteel);
        putSteel.setText("PUT STEEL");

        buttonGroup1.add(putWater);
        putWater.setText("PUT WATER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walk)
                    .addComponent(putBrick)
                    .addComponent(putSteel)
                    .addComponent(putWater))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(walk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(putBrick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(putSteel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(putWater)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1375, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        //BattleField needs to be painted all the time
        //  battleFieldPainter = new Timer(2, new BattleFieldPainter());
        //  battleFieldPainter.start();
    }
    int tankCount = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Go = true;
        tikerKeeper = 0;
        jButton6.requestFocus();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CityPlaner cityPlaner = new CityPlaner("CityPlaner", 0, 0);
        battleField.tanksOnField.put(cityPlaner.getTANK_NUMBER(), cityPlaner);
        jButton6.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Block block;
        for (int a = 0; a < 800; a += 20) {

            for (int b = 100; b < 700; b += 20) {
                if (b < 120) {
                    block = new Block("Water", a, b);
                } else if (b < 600) {
                    block = new Block("Brick", a, b);
                } else {
                    block = new Block("Steel", a, b);
                }

                BattleField.cityPlan.put(block.getBLOCK_NUMBER(), block);
                ArrayList<Particle> hull = block.getHull();
                for (Particle particle : hull) {
                    BattleField.matrix[a + particle.getX()][b + particle.getY()] = particle;
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        battleField.myNewTank();
        jButton6.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton putBrick;
    public static javax.swing.JRadioButton putSteel;
    public static javax.swing.JRadioButton putWater;
    public static javax.swing.JRadioButton walk;
    // End of variables declaration//GEN-END:variables

    class GameTicker implements Runnable {

        @Override
        public void run() {
            int a = 0;
            tikerKeeper = 0;
            while (true) {
                battleField.repaint();

                //----
                Iterator tankIt = BattleField.tanksOnField.entrySet().iterator();
                while (tankIt.hasNext()) {
                    Map.Entry pair = (Map.Entry) tankIt.next();
                    Tank tank = (Tank) pair.getValue();
                    if (tank.getStatus().equals("active")) {
                        tank.tik();
                    }
                }
//----

                Iterator it = BattleField.explosionsList.entrySet().iterator();
                while (it.hasNext()) {

                    Map.Entry pair = (Map.Entry) it.next();
                    Animation animation = (Animation) pair.getValue();
                    if (animation.getExplosionPower() == 1) {
                        it.remove();// avoids a ConcurrentModificationException
                    } else {
                        animation.reduceExplosionPower();
                    }
                }
                try {
                    thread.sleep(3);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                tikerKeeper++;

                if (Go) {

                    if (tikerKeeper == 1 || tikerKeeper == 10000 || tikerKeeper == 20000) {
                        battleField.newTank("T1", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 50 || tikerKeeper == 10050 || tikerKeeper == 20050) {
                        battleField.newTank("T1", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 100 || tikerKeeper == 10100 || tikerKeeper == 20100) {
                        battleField.newTank("T1", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 150 || tikerKeeper == 10150 || tikerKeeper == 20150) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 200 || tikerKeeper == 10200 || tikerKeeper == 20200) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 250 || tikerKeeper == 10250 || tikerKeeper == 20250) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 300 || tikerKeeper == 10300 || tikerKeeper == 20300) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 350 || tikerKeeper == 10350 || tikerKeeper == 20350) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 400 || tikerKeeper == 10400 || tikerKeeper == 20400) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 450 || tikerKeeper == 10450 || tikerKeeper == 20450) {
                        battleField.newTank("T2", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 500 || tikerKeeper == 10500 || tikerKeeper == 20500) {
                        battleField.newTank("T3", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 550 || tikerKeeper == 10550 || tikerKeeper == 20550) {
                        battleField.newTank("T3", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 600 || tikerKeeper == 10600 || tikerKeeper == 20600) {
                        battleField.newTank("T3", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 650 || tikerKeeper == 10650 || tikerKeeper == 20650) {
                        battleField.newTank("T3", a);
                        a = a + 1;
                    }
                    if (tikerKeeper == 700 || tikerKeeper == 10700) {
                        battleField.newTank("T3", a);
                        a = 0;
                    }
                }
            }
        }
    }
}
